# Prometheus Configuration for Complyo Production Monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'complyo-production'
    replica: 'prometheus-01'

# Rules for alerting
rule_files:
  - "alert_rules.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: '/metrics'

  # Complyo Backend API monitoring
  - job_name: 'complyo-backend'
    static_configs:
      - targets: ['complyo-backend-direct:8002']
    scrape_interval: 10s
    metrics_path: '/metrics'
    scrape_timeout: 5s
    params:
      format: ['prometheus']
    basic_auth:
      username: 'prometheus'
      password: 'monitoring_secret'

  # Nginx Gateway monitoring
  - job_name: 'nginx-gateway'
    static_configs:
      - targets: ['complyo-gateway:8080']
    scrape_interval: 10s
    metrics_path: '/nginx-status'
    scrape_timeout: 5s

  # PostgreSQL monitoring (using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 10s

  # Redis monitoring (using redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 10s

  # Node metrics (system monitoring)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s

  # Docker container monitoring
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 10s
    metrics_path: '/metrics'

  # Frontend application monitoring (if metrics endpoint available)
  - job_name: 'complyo-dashboard'
    static_configs:
      - targets: ['complyo-dashboard:3000']
    scrape_interval: 30s
    metrics_path: '/api/metrics'
    scrape_timeout: 10s

  # Landing page monitoring
  - job_name: 'complyo-landing'
    static_configs:
      - targets: ['complyo-landing:3001']
    scrape_interval: 30s
    metrics_path: '/api/metrics'
    scrape_timeout: 10s

  # SSL certificate monitoring
  - job_name: 'ssl-exporter'
    static_configs:
      - targets: ['ssl-exporter:9219']
    scrape_interval: 60s

  # External services monitoring
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://complyo.tech
        - https://api.complyo.tech
        - https://app.complyo.tech
        - https://api.complyo.tech/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 30d
    retention.size: 10GB

# Remote write configuration (optional - for long-term storage)
# remote_write:
#   - url: "https://your-remote-storage-endpoint/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"