"""
AI-powered Alt-Text Generator
Nutzt OpenAI Vision API für intelligente Alt-Text-Vorschläge
"""

import os
import base64
import logging
from typing import Optional, Dict, Any
import aiohttp
import asyncio

logger = logging.getLogger(__name__)


class AIAltTextGenerator:
    """Generiert Alt-Texte mittels OpenAI Vision API"""
    
    def __init__(self, api_key: Optional[str] = None):
        """
        Initialisiert Generator
        
        Args:
            api_key: OpenAI API Key (falls None, wird aus ENV gelesen)
        """
        self.api_key = api_key or os.getenv('OPENAI_API_KEY')
        self.api_url = 'https://api.openai.com/v1/chat/completions'
        self.model = 'gpt-4o-mini'  # Kosteneffizientes Modell mit Vision
        self.max_tokens = 100
        
    async def generate_alt_text(
        self, 
        image_url: str, 
        context: Optional[str] = None,
        language: str = 'de'
    ) -> Dict[str, Any]:
        """
        Generiert Alt-Text für Bild von URL
        
        Args:
            image_url: URL des Bildes
            context: Optionaler Kontext (umgebender Text)
            language: Sprache für Alt-Text (de/en)
            
        Returns:
            Dict mit 'alt_text', 'confidence' und 'reasoning'
        """
        if not self.api_key:
            logger.warning("No OpenAI API key configured, falling back to basic generation")
            return {
                'alt_text': 'Bild',
                'confidence': 0.3,
                'reasoning': 'No AI available',
                'source': 'fallback'
            }
        
        try:
            prompt = self._build_prompt(context, language)
            
            async with aiohttp.ClientSession() as session:
                headers = {
                    'Authorization': f'Bearer {self.api_key}',
                    'Content-Type': 'application/json'
                }
                
                payload = {
                    'model': self.model,
                    'messages': [
                        {
                            'role': 'user',
                            'content': [
                                {
                                    'type': 'text',
                                    'text': prompt
                                },
                                {
                                    'type': 'image_url',
                                    'image_url': {
                                        'url': image_url,
                                        'detail': 'low'  # Kostenoptimiert
                                    }
                                }
                            ]
                        }
                    ],
                    'max_tokens': self.max_tokens,
                    'temperature': 0.3  # Konsistente Ergebnisse
                }
                
                async with session.post(
                    self.api_url, 
                    headers=headers, 
                    json=payload,
                    timeout=aiohttp.ClientTimeout(total=30)
                ) as response:
                    if response.status != 200:
                        error_text = await response.text()
                        logger.error(f"OpenAI API error {response.status}: {error_text}")
                        return self._fallback_response()
                    
                    data = await response.json()
                    
                    # Extrahiere Antwort
                    alt_text = data['choices'][0]['message']['content'].strip()
                    
                    # Validierung und Bereinigung
                    alt_text = self._clean_alt_text(alt_text)
                    
                    return {
                        'alt_text': alt_text,
                        'confidence': 0.9,
                        'reasoning': 'Generated by AI Vision',
                        'source': 'openai_vision',
                        'model': self.model
                    }
                    
        except asyncio.TimeoutError:
            logger.warning("OpenAI API timeout")
            return self._fallback_response()
        except Exception as e:
            logger.error(f"AI Alt-Text generation failed: {e}")
            return self._fallback_response()
    
    async def generate_alt_text_from_base64(
        self,
        image_base64: str,
        context: Optional[str] = None,
        language: str = 'de'
    ) -> Dict[str, Any]:
        """
        Generiert Alt-Text für Bild von Base64-String
        
        Args:
            image_base64: Base64-kodiertes Bild
            context: Optionaler Kontext
            language: Sprache für Alt-Text
            
        Returns:
            Dict mit Alt-Text-Informationen
        """
        if not self.api_key:
            return self._fallback_response()
        
        try:
            # Prüfe ob base64 data-url prefix hat
            if not image_base64.startswith('data:image'):
                # Füge prefix hinzu (PNG angenommen)
                image_base64 = f'data:image/png;base64,{image_base64}'
            
            prompt = self._build_prompt(context, language)
            
            async with aiohttp.ClientSession() as session:
                headers = {
                    'Authorization': f'Bearer {self.api_key}',
                    'Content-Type': 'application/json'
                }
                
                payload = {
                    'model': self.model,
                    'messages': [
                        {
                            'role': 'user',
                            'content': [
                                {
                                    'type': 'text',
                                    'text': prompt
                                },
                                {
                                    'type': 'image_url',
                                    'image_url': {
                                        'url': image_base64,
                                        'detail': 'low'
                                    }
                                }
                            ]
                        }
                    ],
                    'max_tokens': self.max_tokens,
                    'temperature': 0.3
                }
                
                async with session.post(
                    self.api_url,
                    headers=headers,
                    json=payload,
                    timeout=aiohttp.ClientTimeout(total=30)
                ) as response:
                    if response.status != 200:
                        return self._fallback_response()
                    
                    data = await response.json()
                    alt_text = data['choices'][0]['message']['content'].strip()
                    alt_text = self._clean_alt_text(alt_text)
                    
                    return {
                        'alt_text': alt_text,
                        'confidence': 0.9,
                        'reasoning': 'Generated by AI Vision',
                        'source': 'openai_vision',
                        'model': self.model
                    }
                    
        except Exception as e:
            logger.error(f"AI Alt-Text generation (base64) failed: {e}")
            return self._fallback_response()
    
    async def generate_batch_alt_texts(
        self,
        images: list[Dict[str, Any]],
        max_concurrent: int = 5
    ) -> list[Dict[str, Any]]:
        """
        Generiert Alt-Texte für mehrere Bilder parallel
        
        Args:
            images: Liste von Dicts mit 'url' oder 'base64' und optional 'context'
            max_concurrent: Max parallele API-Calls
            
        Returns:
            Liste mit generierten Alt-Texten
        """
        semaphore = asyncio.Semaphore(max_concurrent)
        
        async def process_image(img_data):
            async with semaphore:
                if 'url' in img_data:
                    return await self.generate_alt_text(
                        img_data['url'],
                        img_data.get('context'),
                        img_data.get('language', 'de')
                    )
                elif 'base64' in img_data:
                    return await self.generate_alt_text_from_base64(
                        img_data['base64'],
                        img_data.get('context'),
                        img_data.get('language', 'de')
                    )
                else:
                    return self._fallback_response()
        
        tasks = [process_image(img) for img in images]
        results = await asyncio.gather(*tasks, return_exceptions=True)
        
        # Filtere Exceptions
        cleaned_results = []
        for result in results:
            if isinstance(result, Exception):
                logger.error(f"Batch generation error: {result}")
                cleaned_results.append(self._fallback_response())
            else:
                cleaned_results.append(result)
        
        return cleaned_results
    
    def _build_prompt(self, context: Optional[str], language: str) -> str:
        """Baut Prompt für AI basierend auf Kontext und Sprache"""
        
        if language == 'de':
            base_prompt = (
                "Beschreibe dieses Bild in 1-2 kurzen, präzisen Sätzen als Alt-Text "
                "für eine barrierefreie Website (WCAG 2.1). "
                "Der Alt-Text sollte informativ und beschreibend sein, aber nicht mit "
                "'Bild von' oder 'Foto von' beginnen."
            )
            
            if context:
                base_prompt += f"\n\nKontext der Webseite: {context[:200]}"
                base_prompt += "\nNutze diesen Kontext, um den Alt-Text relevanter zu machen."
        else:
            base_prompt = (
                "Describe this image in 1-2 short, precise sentences as alt-text "
                "for an accessible website (WCAG 2.1). "
                "The alt-text should be informative and descriptive, but not start with "
                "'Image of' or 'Photo of'."
            )
            
            if context:
                base_prompt += f"\n\nPage context: {context[:200]}"
                base_prompt += "\nUse this context to make the alt-text more relevant."
        
        return base_prompt
    
    def _clean_alt_text(self, alt_text: str) -> str:
        """
        Bereinigt und validiert generierten Alt-Text
        
        Args:
            alt_text: Roher Alt-Text von AI
            
        Returns:
            Bereinigter Alt-Text
        """
        # Entferne führende/trailing whitespace
        alt_text = alt_text.strip()
        
        # Entferne Anführungszeichen am Anfang/Ende
        alt_text = alt_text.strip('"\'')
        
        # Entferne "Alt-Text:" prefix falls vorhanden
        prefixes_to_remove = [
            'Alt-Text:',
            'Alt text:',
            'Alternative Text:',
            'Beschreibung:',
            'Description:'
        ]
        for prefix in prefixes_to_remove:
            if alt_text.startswith(prefix):
                alt_text = alt_text[len(prefix):].strip()
        
        # Limitiere Länge (WCAG Empfehlung: max 150 Zeichen)
        if len(alt_text) > 150:
            # Schneide bei letztem Satzende innerhalb der Grenze
            truncated = alt_text[:147]
            last_period = truncated.rfind('.')
            if last_period > 50:  # Mindestens 50 Zeichen behalten
                alt_text = truncated[:last_period + 1]
            else:
                alt_text = truncated + '...'
        
        # Validierung: Mindestlänge
        if len(alt_text) < 3:
            return "Bild"
        
        return alt_text
    
    def _fallback_response(self) -> Dict[str, Any]:
        """Fallback wenn AI nicht verfügbar"""
        return {
            'alt_text': 'Bild',
            'confidence': 0.2,
            'reasoning': 'AI not available, using fallback',
            'source': 'fallback'
        }


# Convenience-Funktionen
async def generate_alt_text_for_url(
    image_url: str,
    context: Optional[str] = None,
    api_key: Optional[str] = None
) -> str:
    """
    Einfache Funktion zum Generieren von Alt-Text
    
    Returns:
        Nur der Alt-Text als String
    """
    generator = AIAltTextGenerator(api_key)
    result = await generator.generate_alt_text(image_url, context)
    return result['alt_text']


async def generate_alt_text_for_base64(
    image_base64: str,
    context: Optional[str] = None,
    api_key: Optional[str] = None
) -> str:
    """
    Einfache Funktion zum Generieren von Alt-Text aus Base64
    
    Returns:
        Nur der Alt-Text als String
    """
    generator = AIAltTextGenerator(api_key)
    result = await generator.generate_alt_text_from_base64(image_base64, context)
    return result['alt_text']

