version: '3.8'

services:
  # Sauberes Frontend
  frontend:
    build:
      context: ./legal/frontend
      dockerfile: Dockerfile
    container_name: complyo-frontend
    environment:
      - VIRTUAL_HOST=complyo.tech,www.complyo.tech
      - LETSENCRYPT_HOST=complyo.tech,www.complyo.tech
      - LETSENCRYPT_EMAIL=admin@panoart360.de
      - VIRTUAL_PORT=80
    networks:
      - proxy-network
      - complyo-network
    restart: unless-stopped
    depends_on:
      - backend

  # Backend (bleibt unverändert)
  backend:
    build:
      context: ./legal
      dockerfile: Dockerfile
    container_name: complyo-backend
    environment:
      - ENVIRONMENT=production
      - PORT=8002
      - DATABASE_URL=postgresql://complyo_user:WrsmZTXYcjt0c7lt%2FlOzEnX1N5rtjRklLYrY8zXmBGo%3D@shared-postgres:5432/complyo_db
      - REDIS_HOST=shared-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=04/jdoPGip+v2Yqoeo0+nNSIvxZsC/u+Q+E4qBrGA0E=
      - REDIS_DB=4
      - JWT_SECRET=9ECBjaQa7KwoyciJtLTQjc/fWRClrsMUXl5LSpIwi+I9y3wPnD1ZAZ6On+WGukAZ2bmkgInnjJjBEeU2xkluEQ==
      - OPENROUTER_API_KEY=YOUR_OPENROUTER_API_KEY
      - ERECHT24_API_KEY=YOUR_ERECHT24_API_KEY
      - VIRTUAL_HOST=api.complyo.tech
      - LETSENCRYPT_HOST=api.complyo.tech
      - LETSENCRYPT_EMAIL=admin@panoart360.de
      - VIRTUAL_PORT=8002
    networks:
      - proxy-network
      - shared-network
      - complyo-network
    restart: unless-stopped

networks:
  proxy-network:
    external: true
  shared-network:
    external: true
  complyo-network:
    driver: bridge
